/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.redhat.example.rules.unittest;

import java.util.Map;

/**
 * ExpectedRecode contains expected information for test.<BR>
 * - map is { attribute -> expected value } relation map as Meta style format.<BR>
 *   Some values could be special meaning. for example, "[null]" means the expected value "should be null".<BR>
 *   and "[empty]" means an empty string (""). (These are implemented.)<BR>
 *   Similarly, it would be extended as if "[not null]", it should NOT be null. (not implemented, yet.) <BR>
 * - fact is the expected result fact generated by the map information<BR>
 * - used is a flag whether this record is used or not.
 * @param <T>
 */
public class ExpectedRecord {
	/**
	 * map is { attribute -> expected value } relation map as Meta style format.<BR>
	 *   Some values could be special meaning. for example, "[null]" means the expected value "should be null".<BR>
	 *   and "[empty]" means an empty string (""). (These are implemented.)<BR>
	 *   Similarly, it would be extended as if "[not null]", it should NOT be null. (not implemented, yet.) <BR>
	 */
	public Map<String, Object> map;
	/**
	 *  - fact is the expected result fact generated by the map information<BR>
	 */
	public Object fact;
	
	/**
	 * used is a flag whether this record is used or not.
	 */
	public boolean used = false;
}