
import java.util.Map;
import java.util.List;
import com.redhat.example.fact.plan.*;

/**
 * 入力Mapから、"CustomerProfileAll" のFACTをインサートする
 */
rule "初期化ルール_CustomerProfileAll"
    when
        Map($list: get("CustomerProfileAll") != null);
    then
		for (Object $f : (List)$list) {
			System.out.println("Insert " + $f);
			insert($f);
		}
end

rule "change map entry"
	when
		CustomerProfileAll($map: map)
	then
		$map.put("追加null", null);
		$map.put("追加empty", "");
end